name: Deploy

on:
  workflow_call:
    inputs:
      aws-access-key-id:
        required: true
        type: string
      aws-secret-access-key:
        required: true
        type: string
      environment:
        required: true
        type: string
      distribution-list-id:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}

      - name: SAM Build and Deploy
        run: |
          npm install -g esbuild
          npm ci

          sam --info
          sam build --parallel

          sam deploy \
          --stack-name newsletter-service \
          --resolve-s3 \
          --no-fail-on-empty-changeset \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides Environment=${{ inputs.environment }} SendGridDistributionListId=${{ inputs.distribution-list-id }}
